### ISSUE TITLE
some bugs in audiolib

### ISSUE THREAD

**Issue by kangcp** [microsoft/MS-SNSD#8]
I think in audiolib file, line 66 code: noisescalar = np.sqrt (rmsclean / (10 ** (snr / 20)) / rmsnoise), 
snr should be divided by 10, not 20.

**Comment by Liu-1994** [comment]
I also think there is something wrong. But maybe it should be "noisescalar = rmsclean / (10 ** (snr / 20)) / rmsnoise", as the "rmsclean" and "rmsnoise" have been square root.

**Comment by chandanka90** [comment]
Recomputed rmsclean and rmsnoise after scaling. Should be good now.
