### ISSUE TITLE
Maybe something wrong in audiolib.py

### ISSUE THREAD

**Issue by Liu-1994** [microsoft/MS-SNSD#9]
For the function **def snr_mixer(clean, noise, snr)** in the **audiolib.py** file, I think there is something wrong.
First, line 66 code: Function **np.sqrt( )** may be unnecessary.
Second, as **clean** and **noise** have been normalized to -25 dBFS, **noisescalar** may not need to be calculated using **rmsclean** and **rmsnoise**.

**Comment by chandanka90** [comment]
Fixed the bug
